### ISSUE TITLE
module not found error: no module named 'reshaper'

### ISSUE THREAD

**Issue by kouchakzadeh** [al1b/Calibre-KiPEO#14]
Hi im facing a problem installing your plugin in calibre 5.2.
the error says:

calibre, version 5.2.0
ERROR: Unhandled exception: <b>ModuleNotFoundError</b>:No module named 'reshaper'

calibre 5.2  embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', 'SP0', 'Multiprocessor Free')
Interface language: None
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "calibre\customize\ui.py", line 472, in add_plugin
  File "calibre\customize\ui.py", line 61, in load_plugin
  File "calibre\customize\zipplugin.py", line 282, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 181, in exec_module
  File "calibre_plugins.dummy1.__init__", line 5, in <module>
ModuleNotFoundError: No module named 'reshaper'

any suggestions?

**Comment by 0x414c49** [comment]
I don't have access to the al1b/Calibre-KiPEO repo now, in another forked
repo I fixed the problem.

https://github.com/0x414c49/Calibre-KiPEO

You can get fixed released version here:
https://github.com/0x414c49/Calibre-KiPEO/releases

**Comment by kouchakzadeh** [comment]
Hi again
I tried the link you sent, when Im trying to install the plugin from Calibre, I get the same error message.

**Comment by al1b** [comment]
Could you create the issue there? I cannot do anything on this repository
cause I don't have access to it anymore.

**Comment by kouchakzadeh** [comment]
is there any way we can communicate through email or phone?
Im actually very curious to find out whats the problem cuz it seems Im the only one who is facing this issue.
my email is amir.kzadeh@yahoo.com
my phone is 9347697386

**Comment by kouchakzadeh** [comment]
Im still facing this issue 
module not found error: No module named "reshaper"

anyone can give me a help?

**Comment by kouchakzadeh** [comment]
Dear Ali Bahraminzadeh, is there any way I can contact you?
Im not a computer expert so i think i need a little bit of yer help if possible

**Comment by 0x414c49** [comment]
Hi,
Sorry for the late reply, I didn’t have time to check it. Please go to this page: https://github.com/0x414c49/Calibre-KiPEO

From the release part download and install it, the bug is solved there.

Unfortunately I don’t have my source code here.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kouchakzadeh** [comment]
Dear Ali
I faced a new error which looks like this

any suggestions?
-Amir Kouchakzadeh

KABA Co.45m Golshahr Ave. Hoshiar BlvdOSTADAN complex, #42
(+98)9123671365
 

    On Sunday, October 18, 2020, 12:42:20 AM GMT+3:30, Ali Bahrami <notifications@github.com> wrote:  
 
 

Hi,
Sorry for the late reply, I didn’t have time to check it. Please go to this page: https://github.com/0x414c49/Calibre-KiPEO

From the release part download and install it, the bug is solved there.

Unfortunately I don’t have my source code here.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by 0x414c49** [comment]
I cannot see your error. Did you try this version?

![image](https://user-images.githubusercontent.com/57097646/96361954-3e82f300-112a-11eb-9f66-49e60b2e3a35.png)


https://github.com/0x414c49/Calibre-KiPEO/releases

**Comment by kouchakzadeh** [comment]
Dear Ali, I tried all versions but non are working propperthe error i got with the V 1.0.2 is the same which corresponds to reshaperbut the previous email which you sent (master version) says:
calibre, version 5.2.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in 'C:\\Users\\Amir Kouchakzadeh\\Downloads\\Calibre-KiPEO-master.zip' is invalid. It does not contain a top-level __init__.py file
calibre 5.2  embedded-python: True is64bit: FalseWindows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')32bit process running on 64bit windows('Windows', '10', '10.0.19041')Python 3.8.5Windows: ('10', '10.0.19041', 'SP0', 'Multiprocessor Free')Interface language: NoneTraceback (most recent call last):  File "calibre\gui2\preferences\plugins.py", line 317, in add_plugin  File "calibre\customize\ui.py", line 472, in add_plugin  File "calibre\customize\ui.py", line 61, in load_plugin  File "calibre\customize\zipplugin.py", line 273, in load  File "calibre\customize\zipplugin.py", line 368, in _locate_codecalibre.customize.InvalidPlugin: The plugin in 'C:\\Users\\Amir Kouchakzadeh\\Downloads\\Calibre-KiPEO-master.zip' is invalid. It does not contain a top-level __init__.py file


-Amir Kouchakzadeh

KABA Co.45m Golshahr Ave. Hoshiar BlvdOSTADAN complex, #42
(+98)9123671365
 

    On Sunday, October 18, 2020, 11:41:29 AM GMT+3:30, Ali Bahrami <notifications@github.com> wrote:  
 
 


I cannot see your error. Did you try this version?



https://github.com/0x414c49/Calibre-KiPEO/releases

**Comment by 0x414c49** [comment]
You are downloading the source code instead of the release I made. If you go to the releases, you can see the zip file. Please download this file: https://github.com/0x414c49/Calibre-KiPEO/releases/download/0.0.2/Calibre-KiPEO-1.0.2.zip

**Comment by kouchakzadeh** [comment]
nope, unfortunately same problem again.is there any way perhaps you can anydesk with me?
-Amir Kouchakzadeh

KABA Co.45m Golshahr Ave. Hoshiar BlvdOSTADAN complex, #42
(+98)9123671365
 

    On Sunday, October 18, 2020, 02:19:57 PM GMT+3:30, Ali Bahrami <notifications@github.com> wrote:  
 
 


You are downloading the source code instead of the release I made. If you go to the releases, you can see the zip file. Please download this file: https://github.com/0x414c49/Calibre-KiPEO/releases/download/0.0.2/Calibre-KiPEO-1.0.2.zip

**Comment by kouchakzadeh** [comment]
still not working, I tried this link too. but i get an error saying no module name reshaper

**Comment by hachicha** [comment]
Hi all, 
I have the same problem : "No module named 'resharper'" 
I am working on Calibre 5.10.1

**Comment by mohamadafzali** [comment]
> still not working, I tried this link too. but i get an error saying no module name reshaper

Hi dear
try to install [calibre 4.23](https://download.calibre-ebook.com/4.23.0/)
and install the latest version of [Calibre-KiPEO](https://github.com/0x414c49/Calibre-KiPEO/releases)

Regrad

**Comment by shaduwu-code** [comment]
@al1b 
I think that the script is outdated, you need to update the code.

**Comment by And1k93** [comment]
HI 
I'm currently on 5.2.8 version and still the same problem of module named reshaper here is my log after trying to install if you have any solution it would be nice :)

 "calibre, version 5.28.0
ERREUR : Exception non gérée: <b>ModuleNotFoundError</b>:No module named 'reshaper'

calibre 5.28 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: fr
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 327, in add_plugin
  File "calibre\customize\ui.py", line 477, in add_plugin
  File "calibre\customize\ui.py", line 65, in load_plugin
  File "calibre\customize\zipplugin.py", line 293, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 192, in exec_module
  File "calibre_plugins.dummy1.__init__", line 5, in <module>
ModuleNotFoundError: No module named 'reshaper'
"
